### ISSUE TITLE
Restored Data Incorrectly

### ISSUE THREAD

**Issue by jsdanie1** [Murloc124/DataRestorationTool#9]
Is this tool purely just creating new records or importing new records with exact prexisting fields. I did a recent restore, and it seems to not restored the status of any of the records. I recently needed to restore a Order and its Order Products. But it keeps telling me the statecode don't match. Then looking at the system it just seems it recreated everything as new and not using its proper statecode and statusreason.

**Comment by Murloc124** [comment]
Hi,
Marking this as duplicate, I'll handle this in Issue#10 that you created.
